name: Deploy Desktop App

on:
  push:
    branches:
      - main

jobs:
  desktop-app:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true

      - name: Build Desktop App
        run: ./gradlew packageDistributionForCurrentOS

      - name: Upload build outputs
        uses: actions/upload-artifact@v4
        with:
          name: desktop-build-binaries
          path: desktop-app/build/compose/binaries
